[package]
name = "kaysentinel-verify"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
kaysentinel-hash = { path = "../hash" }
kaysentinel-cse = { path = "../cse" }
kaysentinel-builder = { path = "../builder" }

[dev-dependencies]
kaysentinel-bridge = { path = "../bridge" }
